# Site settings
title: Soreine
email: hello@soreine.dev
description: "Soreine's personal website" # > this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://soreine.dev" # the base hostname & protocol for your site
github_username: Soreine
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/
  - node_modules/
  - package.json
  - package-lock.json
# Build settings
markdown: kramdown
highlighter: rouge
breadcrumbs:
  root:
    hide: false # show breadcrumbs on root/home page
    image: false # Show image or title text
